# Fundamentos de Inteligencia Artificial - Reto Connect-4
_**Universidad de La Sabana**_

## Integrantes
- Felipe Ballesteros
- Sebastián Piñeros
- Sergio Socha

In [32]:
import json
import numpy as np
from connect4.connect_state import ConnectState


In [ ]:
results_path = "versus"

juegos = []

for file in os.listdir(results_path):
    if file.endswith(".json"):
        with open(os.path.join(results_path, file), "r", encoding="utf-8") as f:
            data = json.load(f)
            juegos.append((filename, data))

        juegos.append({
            "match_file": file,
            "player_a": data["player_a"],
            "player_b": data["player_b"],
            "player_a_wins": data["player_a_wins"],
            "player_b_wins": data["player_b_wins"],
            "draws": data["draws"],
            "num_games": len(data["games"])
        })

df_matches = pd.DataFrame(juegos)
df_matches



            

match_file player_a player_b  player_a_wins  \
0  match_Group B_vs_Group D.json  Group B  Group D              0   
1  match_Group C_vs_Group A.json  Group C  Group A              4   
2  match_Group D_vs_Group C.json  Group D  Group C              4   
3  match_Group D_vs_Group E.json  Group D  Group E              4   
4  match_Group E_vs_Group A.json  Group E  Group A              4   
5  match_Group E_vs_Group C.json  Group E  Group C              4   
6  match_Group F_vs_Group C.json  Group F  Group C              4   
7  match_Group F_vs_Group D.json  Group F  Group D              1   
8  match_Group F_vs_Group E.json  Group F  Group E              4   

   player_b_wins  draws  num_games  
0              4      0          4  
1              2      0          6  
2              0      0          4  
3              3      2          9  
4              0      0          4  
5              0      0          4  
6              0      0          4  
7              4      0          5  
8              3      0          7

In [ ]:
versus_path = "versus"

juegos = []

for filename in os.listdir(versus_path):
    if filename.endswith(".json"):
        with open(os.path.join(versus_path, filename)) as f:
            data = json.load(f)
            juegos.append((filename, data))


In [47]:
def print_board(board):
    print(np.array(board))


In [48]:
def get_final_state(game_steps):
    final_board, last_col = game_steps[-1]
    return final_board, last_col


In [49]:
def count_moves(game_steps):
    return len(game_steps)


In [50]:
def replay_game(game_steps):
    for i, (board, col) in enumerate(game_steps):
        print(f"\n=== Movimiento {i+1} (columna {col}) ===")
        print_board(board)


In [51]:
def get_last_player(game_steps):
    return 1 if len(game_steps) % 2 == 1 else -1


In [52]:
def show_game_info(match, game_index=0):
    filename, data = match

    print("\n======================================")
    print("Match:", filename)
    print("Player A:", data["player_a"])
    print("Player B:", data["player_b"])
    print("A wins:", data["player_a_wins"])
    print("B wins:", data["player_b_wins"])
    print("Draws:", data["draws"])
    print("Cantidad de juegos:", len(data["games"]))

    game_steps = data["games"][game_index]

    print(f"\n====== Juego {game_index + 1} ======")

    final_board, last_col = get_final_state(game_steps)

    print("\nEstado final:")
    print_board(final_board)

    print("\nÚltima columna jugada:", last_col)
    print("Total movimientos:", count_moves(game_steps))
    print("Último jugador:", get_last_player(game_steps))


In [55]:
matches_F = []

for match in juegos:
    filename, data = match
    if "Group F" in data["player_a"] or "Group F" in data["player_b"]:
        matches_F.append(match)

print("Matches del Grupo F encontrados:", len(matches_F))


Matches del Grupo F encontrados: 3


In [56]:
for match in matches_F:
    show_game_info(match)



Match: match_Group F_vs_Group C.json
Player A: Group F
Player B: Group C
A wins: 4
B wins: 0
Draws: 0
Cantidad de juegos: 4

====== Juego 1 ======

Estado final:
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0]
 [ 0  0  0 -1  0  0  0]
 [ 0  0 -1 -1 -1  1  0]
 [ 0  1 -1 -1  1  1  1]]

Última columna jugada: 1
Total movimientos: 13
Último jugador: 1

Match: match_Group F_vs_Group D.json
Player A: Group F
Player B: Group D
A wins: 1
B wins: 4
Draws: 0
Cantidad de juegos: 5

====== Juego 1 ======

Estado final:
[[-1  0 -1 -1  1  0  1]
 [ 1  0 -1  1  1  0 -1]
 [ 1  0 -1 -1 -1  0  1]
 [-1  0  1 -1  1 -1 -1]
 [-1  1  1  1 -1  1 -1]
 [-1  1  1 -1  1  1 -1]]

Última columna jugada: 5
Total movimientos: 36
Último jugador: -1

Match: match_Group F_vs_Group E.json
Player A: Group F
Player B: Group E
A wins: 4
B wins: 3
Draws: 0
Cantidad de juegos: 7

====== Juego 1 ======

Estado final:
[[ 0  0 -1 -1 -1  0  0]
 [-1  0  1  1  1  0  0]
 [ 1  0 -1 -1 -1  0 -1]
 [-1  0 -1 -1  1

In [57]:
total_matches = len(juegos)

avg_moves = np.mean([
    len(match_data["games"][0]) 
    for _, match_data in juegos
])

wins_A = sum(data["player_a_wins"] for _, data in juegos)
wins_B = sum(data["player_b_wins"] for _, data in juegos)

print("Total de matches:", total_matches)
print("Promedio de movimientos por juego:", avg_moves)
print("Victorias totales Player A:", wins_A)
print("Victorias totales Player B:", wins_B)


Total de matches: 9
Promedio de movimientos por juego: 18.77777777777778
Victorias totales Player A: 29
Victorias totales Player B: 16
